### ISSUE TITLE
Error ENOENT after installing globally

### ISSUE THREAD

**Issue by colinsmith** [mvsde/mailbox#1]
I've installed this package globally via Yarn, but both `build` and `dev` commands seem to be passing incorrect paths to the render function, causing an `ENOENT` error. Is this a known issue?

After some digging, I've managed to get it working by updating the `generateTemplatePath()` path value to include the layout name, and passing the layout option to several of the commands to allow assets to render correctly. This seems to have resolved the issue.

I'm happy to open a PR with my changes to review if it helps!

**Comment by mvsde** [comment]
First of all: thanks for reporting an issue :)

Unfortunately, I couldn't reproduce the problem, unless I specified a layout which doesn't exist. This led to the following error message:

```
$ mailbox build test
i Rendering MJML…                                                                                  08:19:27
C:\Users\fynn-\AppData\Local\Yarn\Data\global\node_modules\yargs\yargs.js:1148
      else throw err
           ^

Error: ENOENT: no such file or directory, open 'src/layouts/test.mjml'
    at Object.openSync (fs.js:451:3)
    at Object.readFileSync (fs.js:351:35)
    at renderMJML (C:\Users\fynn-\AppData\Local\Yarn\Data\global\node_modules\@mvsde\mailbox\lib\render-mjml.js:19:23)
    at build (C:\Users\fynn-\AppData\Local\Yarn\Data\global\node_modules\@mvsde\mailbox\commands\build.js:15:18)
    at Object.handler (C:\Users\fynn-\AppData\Local\Yarn\Data\global\node_modules\@mvsde\mailbox\bin\mailbox.js:34:33)
    at Object.runCommand (C:\Users\fynn-\AppData\Local\Yarn\Data\global\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (C:\Users\fynn-\AppData\Local\Yarn\Data\global\node_modules\yargs\yargs.js:1063:30)
    at Object.parse (C:\Users\fynn-\AppData\Local\Yarn\Data\global\node_modules\yargs\yargs.js:542:19)
    at Object.<anonymous> (C:\Users\fynn-\AppData\Local\Yarn\Data\global\node_modules\@mvsde\mailbox\bin\mailbox.js:141:4)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
```

Is this the same message you got?

I discovered and fixed some problems with the readme file, mainly the wrong file extension for layouts (`.json` instead of the correct `.mjml`). Maybe this was related to your issue?

Thanks in advance for all information you can provide, so that I am able to understand the issue.

**Comment by colinsmith** [comment]
That is the error I received, yes.

My repro steps are:

1. Install globally with `yarn global add @mvsde/mailbox`
2. `mkdir example && cd example` in any working directory
3. `mailbox create example`
4. `mailbox build example`

Running the `build` command throws the following error:

```
/Users/colin/.config/yarn/global/node_modules/yargs/yargs.js:1148
      else throw err
           ^

Error: ENOENT: no such file or directory, open 'src/layouts/example.mjml'
    at Object.fs.openSync (fs.js:579:3)
    at Object.fs.readFileSync (fs.js:485:33)
    at renderMJML (/Users/colin/.config/yarn/global/node_modules/@mvsde/mailbox/lib/render-mjml.js:19:23)
    at build (/Users/colin/.config/yarn/global/node_modules/@mvsde/mailbox/commands/build.js:15:18)
    at Object.handler (/Users/colin/.config/yarn/global/node_modules/@mvsde/mailbox/bin/mailbox.js:34:33)
    at Object.runCommand (/Users/colin/.config/yarn/global/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/Users/colin/.config/yarn/global/node_modules/yargs/yargs.js:1063:30)
    at Object.parse (/Users/colin/.config/yarn/global/node_modules/yargs/yargs.js:542:19)
    at Object.<anonymous> (/Users/colin/.config/yarn/global/node_modules/@mvsde/mailbox/bin/mailbox.js:141:4)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
```

From what I've been able to see, there are two things at play here.

The path is incorrect *and* the root `.mjml` file is not created with the same name as the project directory. The `layout` option is not passed to the `generateTemplatePath()` function, so it incorrectly attempts to build from `/src/layouts/example.mjml` instead of `example/src/layouts/default.mjml`

Let me know if you're able to reproduce the same thing! 👍 Thanks!

**Edit:** Forgot to mention my environment details (I see you are testing on Windows). I'm using:
* MacOS Sierra
* Node v10.4.0

**Comment by mvsde** [comment]
Thank you for the steps! Now I know whats wrong: my documentation isn't clear enough :D

The command `mailbox create example` creates a new folder in the current working directory called `example`. The project is then placed within this new folder. If you want to place the project in the current directory, you can call `mailbox create` or `mailbox create .`.

And further on, I think the documentation isn't clear that you don't have to specify a layout for the commands `dev`, `build` and `test`.

I already overhauled the readme file.  I hope this resolves any issues.

Thanks again for bringing this up :)

**Comment by colinsmith** [comment]
Ahhh, okay that makes *a lot* more sense! Thanks for clearing that up! 🎉
